### ISSUE TITLE
Custom Pack Export Issue

### ISSUE THREAD

**Issue by DaveSpud** [battlecatsultimate/BCU-java-PC#100]
Hi, following the tutorial at item 4.5 'finishing up'. Clicking on 'export' a pop up appears asking about passwords. I click through this to save but the packs folder remains empty. 
Instead a BCUZIP file appears in the export folder entitled XXXX.pack. This has the internet explorer symbol attached, is only 4KB and opening or saving repeatedly opens my downloads folder.

**Comment by MandarinSmell** [comment]
Are you sure it's not pack.bcuzip file? Or is it just that file browser isn't showing extension?

https://support.microsoft.com/en-us/windows/common-file-name-extensions-in-windows-da4a4430-8e76-89c5-59f7-1cdbbc75cb01

Because you have to make it show extension manially, otherwise that config is turned off as default. Also, being connected with internet browser is what you did, not any error nor problem from BCU

**Comment by nicermak** [comment]
Maybe you didn't turn on the file extension display.
The pack folder is used to import pack.bcuzip.

**Comment by MandarinSmell** [comment]
Closing issue due to discontinued discussion
