### ISSUE TITLE
[Suggestion] Ignore tech limits and a few other cheaty things (for fun and easy testing)

### ISSUE THREAD

**Issue by IceandFire04** [battlecatsultimate/BCU-java-PC#101]
Options like these would be very interesting to see in BCU as a little section in settings because you wouldn't have to use a save editor or GameGuardian to experiment with battle cats.
List of cheats that would be cool:

- In-battle cat/enemy stat changing (basically typing in numbers on the right and left sides of the battle area)
- Free cats
- No cat cooldown
- No tech limit (stuff like research and worker cat stuff)
- No cat attack cooldown
And probably a lot more specific stuff

Preventing people from passing something off as legit:
Maybe add a little indicator where the powers usually go that could be a little image of hacker cat or something

Hopefully, you could implement these in some way :D

**Comment by MandarinSmell** [comment]
`For fun` has always been denied because all devs are working on BCU with sparing our times. BCU's main contents is custom contents, and that's true

But devs, at least I, put more focus on replicating BC as accurate as possible. So we don't prefer implementing such game breaking feature to BCU since it isn't useful for most of time, but it's rather for fun as you said. We want to spare our time on more valuable feature

1. In-battle stat change

This can't work. To optimize memory, BCU refers to already stored data. If we touch this data, that means further usage of said data will get affected by it too. Also attack and hp themselves are pre-defined in the battle

2. Free cats

I don't know what this means. For now, touching data of BC can't be done due to reason above. You have to create your own custom unit, and use them instead. Just set cost as 0, or 1 if 0 doesn't work

3. No cat cooldown

Yes, BC also has unlimiting cooldown for 1 minute from cat god feature, but that doesn't mean it will be good feature to BCU, and nobody uses cat god anyway since they require cat foods regardless of costs

4. Unlimited tech levels

Nope, same reason with 3. BCU uses integer or float for values. These values can't have insanely large numbers. Otherwise it will overflow or underflow, which can bring big problems, or even, crash. Unlocking tech levels means formula can give ridiculously large value, so overflow problem can happen

5. No cat attack cooldown

Keep in mind that BC is hardly bound with status of animations. If we force BCU to disconnect symchronization between data flow and animations, it will rather bring severe bug in battle codes, so attack animations and timings must be bound each other strictly. We can't "just" reduce attack cooldown. Again, you can achieve this via creating your own short-lengthed animation and 0 TBA value in stat

**Comment by IceandFire04** [comment]
Okay, thanks! Still working on ideas that would be cool. Might have to research other closed issues. Thanks for your help! :D
