### ISSUE TITLE
Null in main?

### ISSUE THREAD

**Issue by WaterbottleMan69** [battlecatsultimate/BCU-java-PC#106]
Hi! I have been trying to get the game to work for a couple of weeks now. and it finally installed version 5-2-18 and it keeps giving me an error saying null in main. I really want to play it! Please help!

**Comment by MandarinSmell** [comment]
If you go to `logs` folder in the folder where BCU exists, you will see bunch of `.log` files. Upload the latest file here, or copy/paste contents of it here

**Comment by WaterbottleMan69** [comment]
failed to download https://github.com/battlecatsultimate/bcu-assets/raw/master/assets/000001.asset.bcuzip
failed to download https://github.com/battlecatsultimate/bcu-assets/raw/master/assets/000005.asset.bcuzip
failed to download https://github.com/battlecatsultimate/bcu-assets/raw/master/assets/000006.asset.bcuzip
failed to download https://github.com/battlecatsultimate/bcu-assets/raw/master/assets/000007.asset.bcuzip
failed to download https://github.com/battlecatsultimate/bcu-assets/raw/master/assets/000008.asset.bcuzip
java.lang.NullPointerException
	at common.util.anim.ImgCut.<init>(ImgCut.java:44)
	at common.util.anim.ImgCut.newIns(ImgCut.java:28)
	at common.util.Res.readData(Res.java:98)
	at common.pack.PackData$DefPack.load(PackData.java:62)
	at main.MainBCU$AdminContext.initProfile(MainBCU.java:103)
	at main.MainBCU.main(MainBCU.java:371)
null in main
version: 0-5-2-18

**Comment by MandarinSmell** [comment]
We store assets in github here, so here's 3 possible factors

1. Your region is China. In this case, you can't download asset data
2. Your anti virus program blocked jar file from accessing internet. Some anti viruses do this just because it's unreliable
3. BCU doesn't have permission to create file, edit file, or delete file. This is either because BCU doesn't have permission to, or it got blocked by anti virus program

Try to add BCU to white list if you are using anti virus program. Or completely delete anti virus if it still blocks BCU

**Comment by WaterbottleMan69** [comment]
oddly the installer worked. so I don't think it doesn't have permission. I don't have a Vpn so I'm not in china. and this is a new computer so I don't have an antivirus yet. It seems I can download them from here so if you could just tell me where to put them that would be great.

**Comment by WaterbottleMan69** [comment]
I download the files and put them into the folder it worked!
