### ISSUE TITLE
Updates 

### ISSUE THREAD

**Issue by tcr6cirs** [battlecatsultimate/BCU-java-PC#60]
Will this app be updated?

**Comment by MandarinSmell** [comment]
It's keep being updated. If you are using 0-4-X-X version, update it to 0-5-X-X.

https://github.com/battlecatsultimate/bcu-assets/blob/master/jar/BCU-Initializer.jar

0. Back up all your BCU files, especially `user`, `res`, `pack`, `replay`, and `backup`. Try to remove corrupted file as possible as you can. Re-export all packs by clicking `export` button in pack management screen

1. Go to link above

2. Download BCU-Initializer and put it into your BCU

3. Run it

It will try to download its own stuffs. To make stuffs clearer, you can just delete `BCU_lib` folder and `assets` folder. It will also try to reformat your packs and external packs, so you can keep continuing custom creations in 0-5-X-X, aka v5. **Be aware that this reformat cannot be undone, and since I already told you to backup data first, we won't take any reponsibilities for losing your data.**

I will close this issue
