### ISSUE TITLE
Issue template /w some comments

### ISSUE THREAD

**Issue by TheEt1234** [battlecatsultimate/BCU-java-PC#67]
By some comments i mean what you shouldn't suggest
It would save some few comments

**Comment by MandarinSmell** [comment]
I don't know what you mean by `suggest`, but if it's about our codes, anything is fine, but you will also have to explain what code structure will be about your suggestion, and if possible, opening pull request with finished code is recommended

**Comment by TheEt1234** [comment]
by suggest i mean something like

"Remove the cooldown limit in the editor" (which of course wouldn't get in) or something like that

**Comment by MandarinSmell** [comment]
That rather will bring broken battle. What is the point of implementing feature allowing users to spawn faster than 2 seconds. If it's merely for fun, we will deny it. We aren't doing this for our job or life. We are sparing time from our own life, so we really don't want something which rather breaks battle. We want something useful, or something which can make battle more perfect than before, or improve battle.

Unlimiting cool down also brings several problem. Some BC units are already getting limited by this 60f cool down limit. If we unlimit this value, these units will also have cool down lower than 60f, leading to incorrect result of battle simulation. We are focusing more on simulating battle, not customizing. Thus yes, BCU is not game, it's more like simulator with offerings of BC data.

If we really have to give example, sure.

1. Implementing sniper item's bullet velocity and delays of sniper attack
2. Implementing 6f delays when spawning units

All these things are happening in BC, yet it doesn't in BCU. Suggestion like these are welcomed

**Comment by ModAltForBCUandBBU** [comment]
Mandarin pls help
How do i make my custom anim play its attack animation while attack? here is what sprite sheet i used and i made and some of the contents
![costume1 (1)](https://user-images.githubusercontent.com/93238229/139008314-0a2fc83c-01ec-4243-9a5c-f5858b18dab5.png)
![maanim](https://user-images.githubusercontent.com/93238229/139008442-7c0ca3a4-f43a-4489-90c4-3792b8c2a99d.JPG)

![contents](https://user-images.githubusercontent.com/93238229/139008452-04ae5026-7d60-414a-9ee6-dbebc5fd4c61.JPG)

**Comment by MandarinSmell** [comment]
If one developer said you to stop opening issues for help, then it's same for me. This decision is done for us, not for that developer only. As developer said, read animation guide in read me in this repository. Also, this issue isn't yours at all, with the fact that you evaded blocking, keep in mind that we can directly block you from our repository. If you keep acting similar like this, we will block you. 

If you really, really want help from users, join discord, and become member. This is not for advertising, it's because that this page isn't something normal users use. This site, again, is for **programmers** reporting bugs or flaws in BCU code, or suggesting better code structure, or opening pull request for useful feature

We still will allow non-discord users to use this site, but for your case, **we already told you the way, and warned you not to bring this back.** We are requesting you to stop doint this, or we will take actions

**Comment by MandarinSmell** [comment]
@TheEt1234 Also, if you read my answer, please close issue to say that you understood about it

**Comment by ModAltForBCUandBBU** [comment]
it did not help :( sorry i already seen

**Comment by ModAltForBCUandBBU** [comment]
it

**Comment by MandarinSmell** [comment]
Still that can't be an excuse. The point that this issue page shouldn't be used for such thing stands

**Comment by MandarinSmell** [comment]
Stop it now, this isn't even your issue, you are messing things up now

**Comment by ModAltForBCUandBBU** [comment]
ok i close it i will be working and making BBU

**Comment by ModAltForBCUandBBU** [comment]
bye

**Comment by iREDMe** [comment]
@ModAltForBCUandBBU Do not advertise your BBU github here. Also, you are not a "Mod Alt" for BCU, so change your username accordingly.
