### ISSUE TITLE
bcu network issue?

### ISSUE THREAD

**Issue by kosephdadoge** [battlecatsultimate/BCU-java-PC#70]
java.lang.Exception: missing required libraries: [000003, 000002, 000001, 000007, 000006, 000005, 000004, 100000, 000009, 091000, 000008, 091001, 090900, 100100, 100002, 100200, 100102, 100201, 100103, 100104, 100203], internet connection required
	at common.io.assets.UpdateCheck.checkAsset(UpdateCheck.java:144)
	at io.BCJSON.check(BCJSON.java:32)
	at main.MainBCU.main(MainBCU.java:188)
version: 0-5-0-30
 
when i try to run the .jar file it tells me im missing the required libraries and i need internet connection but my internet is on, what seems to be the issue?

**Comment by MandarinSmell** [comment]
First of all, you are using old version. Download BCU-Initializer from link below to get the latest version. Update BCU first, then report the problem here, currently the latest version is 0-5-1-12

https://github.com/battlecatsultimate/bcu-assets/blob/master/jar/BCU-Initializer.jar

It's recommended to join discord server because all of announcements and release change logs are written in there, so you can get such news quickly. Asset problem can happen when your BCU can't access to internet. Usually there are 2 main factors which can cause this problem

1. Your region is China, so BCU can't access github because China blocked github. Even though you may use VPN, Java can't access internet with VPN

2. Anti virus program is blocking BCU from accessing internet. This happens because anti virus thinks uncertificated executable programs are always dangerous while this isn't always true. BCU isn't certificated, yet it doesn't have any harmful codes in itself. Usually these types of anti virus programs aren't efficient, or good at protecting your computer. You can try to add BCU to white list, but usually this didn't work for users who had same problem. If white listing doesn't work, then only way is removing anti virus program

**Comment by kosephdadoge** [comment]
right just as a follow up getting the newest version worked for me, my region is china but my vpn has a stealth function so that also worked, thanks for the help!
