### ISSUE TITLE
Crash when viewing animation with JOGL on

### ISSUE THREAD

**Issue by unbiaseduser** [battlecatsultimate/BCU-java-PC#73]
I don't know if this has been reported before, but this bug is still happening so I'm doing it anyway.
When I turn JOGL on, any attempts to view unit animations or play a stage causes the app to crash. It doesn't happen with JOGL off.
Here's the log of the crash:
[20220525155227.log](https://github.com/battlecatsultimate/BCU-java-PC/files/8769534/20220525155227.log)

**Comment by MandarinSmell** [comment]
This is because jar file is connected with JDK. If you use too new JDK (JDK 9 or higher), this problem happens. This isn't problem from our codes, but from JOGL library, meaning that this isn't something we can fix it. 

To solve this problem, you have to delete JDK via proper uninstaller (Control Panel, etc.), and reinstall Java with JRE

 * Delete all JDK and JRE to remove registered system properties, so jar file will be disconnected from installed JDK
    - Be aware that **you must not** delete JDK and JRE files manually. You have to use proper uninstaller, and usually Control Panel can handle that
    - If uninstaller asks you to restart PC, restart it. Do not skip this process
    - It doesn't matter whether you have several JRE/JDK or not. Delete all of them
 * After deletion is done, go to [Link here](https://www.java.com/en/download/manual.jsp) and download JRE installer considering your OS
    - If your OS is Windows 64bit, then you must download `Windows Offline (64-bit)` one
 * Once installation is done, try to run BCU by double clicking jar file, and test if JOGL works fine

**Comment by unbiaseduser** [comment]
Thanks, it worked. Turns out I did have a new JDK installed.
