### ISSUE TITLE
Why are my frames so terrible when i open large screen?

### ISSUE THREAD

**Issue by RoundBoundHound** [battlecatsultimate/BCU-java-PC#77]
Also i sometimes get this weird thing where is says Java heap space and then crashes.
Heres the picture of my frames being terrible.
![B Screenshot 2022 08 21 - 12 05 23 78](https://user-images.githubusercontent.com/111685040/185788119-d0ecbf7b-3de8-4293-857b-1c6a2a832eb9.png)

**Comment by RoundBoundHound** [comment]
i just realised you cant see the frames being bad but trust me they are.
Also note it says "time cost 600%" in the top right when im in large screen

**Comment by MandarinSmell** [comment]
For java heap space problem, it's because BCU lacked memory space. This can happen due to either bad computer spec (especially RAM), or incorrectly installed Java. You need to check how much memory space there is in main menu of BCU, left upper corner. There's text saying `Memory used : XXX / MMM` where `MMM` value is BCU's max memory space. You have to check if this max memory space value is around 25% of your RAM size. For example, if your RAM is 8GB, then `MMM` value in BCU should be around 2048, such as 1927, 2035, etc.

If its value is around 256 no matter what despite RAM being higher than 1GB, then that means you installed incorrect Java, especially when your OS is Windows. Tell me if it's not correctly installed, then I will guide you how to reinstall Java properly, you have to do some stuffs before reinstalling it

For `time cost` problem, you can turn on JOGL in config. That will reduce lags by a lot

**Comment by RoundBoundHound** [comment]
Yeah it was java that i installed incorrectly and then i think i installed it correctly now but when loading bcu it wont get past "downloading BCU library gluegen-rt-2.3.2-natives-linux-armv6.jar"

**Comment by RoundBoundHound** [comment]
Nevermind i somehow fixed it thanks!
