### ISSUE TITLE
Initializer Can Not Recognize System Proxy Automatically

### ISSUE THREAD

**Issue by ClementLevi** [battlecatsultimate/BCU-java-PC#95]
On the first running, it failed to connect to the internet although I have configured system proxy. Ultimately solved by using unconditional global proxy to download required libraries. 

Hope there will be a configuration item to enable specific HTTP proxy!

**Comment by MandarinSmell** [comment]
All of the devs here are working on this program for learning Java, or development experiences. None of us haven't set up any proxies, and we haven't had any needs to do, thus all of us don't have good knowledge to support custom proxy configuration. 

Java itself doesn't have *stable* way to get proxy configuration from system, and it also doesn't have capability to automatically detect such. It's rather weird for users to show proxy setting just to download simple assets from github, most of all, users can't pass to main menu (where configuration is existing) without downloading required assets from there

As you said, just using global proxy of course would solve problem, and the files that are downloaded are all from github (if you configured it due to securities or whatever the reason). I'd assume temporarily disabling configured proxy won't be really problem? Simply, it's really rare or minor case for supporting the feature that we barely have knowledge about it

This applies same to VPN

**Comment by MandarinSmell** [comment]
Closing issue due to discontinued discussion
